
name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arnolan
          password: YXJub2xhbjpnaHBfZFVwcVlmTG5VVzdUb1ZDcHZZM3VUOGZVZnhqd0hsMnA4NHBH
      - name: Docker pull and push
        run: |
          docker pull k8s.gcr.io/ingress-nginx/controller:v0.35.0  
          docker tag  k8s.gcr.io/ingress-nginx/controller:v0.35.0  ghcr.io/arnolan/ingress-nginx/controller:v0.35.0       
          docker push ghcr.io/arnolan/ingress-nginx/controller:v0.35.0
          docker pull k8s.gcr.io/defaultbackend-amd64:1.5
          docker tag k8s.gcr.io/defaultbackend-amd64:1.5 ghcr.io/arnolan/defaultbackend-amd64:1.5
          docker push ghcr.io/arnolan/defaultbackend-amd64:1.5
